# Docker compose для быстрой локальной сборки и запуска фронтенда

services:
  frontend:
    image: gigachill-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      additional_contexts:
        openapi: ../openapi
    ports:
      - "3000:3000"
    environment:
      - PORT=3000